export const AXIOS_START='AXIOS/START/SHOP'
export const AXIOS_SUCCESS='AXIOS/SUCCESS/SHOP'
export const AXIOS_FAIL='AXIOS/FAIL/SHOP'
export const CHANGE_INDEX='CHANGE/INDEX/SHOP'
export const CHANGE_SHOP='CHANGE/SHOP'  //点击获取分类名